add service monitor and rewrite some small parts in the templates to …
vikingco/prometheus-lighthouse-exporter pull request #2
Opened 2021-05-18 13:29 UTC by jellevanhees

Created template an values to enable a Prometheus service monitor.
Also made small changes to the existing templates for values that were recurring in multiple templates.

2021-05-18 15:02 UTC, pieterdd reviewed
If you have questions, feel free to Slack me.

2021-05-18 15:02 UTC, pieterdd commented on k8s/helm/prometheus-lighthouse-exporter/templates/deployment.yaml
> +        app: {{ .Values.lighthouse.fullName }}
Any reason why this would be different between environments? If not, I'd only extract environment-specific config.

2021-05-18 15:02 UTC, pieterdd commented on k8s/helm/prometheus-lighthouse-exporter/templates/service.yaml
> +      targetPort: {{ .Values.lighthouse.port }}
Similar remark: I'd keep the constants here as they will be the same on all environments, keeping configuration to a minimum.

2021-05-20 05:41 UTC, jellevanhees commented on k8s/helm/prometheus-lighthouse-exporter/templates/deployment.yaml
> +        app: {{ .Values.lighthouse.fullName }}
the main reason for using these values in my opinion is that should you ever change the value you can do so in one place.
same for ports. 

right now you have to keep in mind that when the name or port changes you have to do so in 3 places. deployment service and service monitor forget one and there is trouble. In this case, it is a very small chart but once they get bigger this becomes a real issue.

2021-05-20 07:17 UTC, pieterdd commented on k8s/helm/prometheus-lighthouse-exporter/templates/deployment.yaml
> +        app: {{ .Values.lighthouse.fullName }}
Ah, you're right. Didn't occur to me that some of these were used in more than one place. This really makes another nice case for a `shared/values.yaml` file, which I'm not certain is possible in SJL's current setup.

2021-05-21 13:14 UTC, pieterdd commented on k8s/helm/prometheus-lighthouse-exporter/templates/deployment.yaml
> +          image: "822523734328.dkr.ecr.eu-west-1.amazonaws.com/prometheus-lighthouse-exporter:{{ .Values.lighthouse.tag }}"
This will not compile, I think you intended to revert to `.Values.tag`.

2021-05-21 13:14 UTC, pieterdd commented on k8s/helm/prometheus-lighthouse-exporter/templates/service.yaml
> +    app: {{ .Values.lighthouse.fullName }}
This will not compile. Did you perhaps mean to use `{{ include "chartGlobals.name" . }}`?

2021-05-26 12:30 UTC, pieterdd requested changes
Looking good! Since we usually don't keep separate fix commits in our Git history, I'll approve this PR after they're squashed together with the commit the fix was for.

2021-05-27 06:05 UTC, pieterdd approved these changes
If the testing phase passes, I will merge.

2021-06-07 09:22 UTC, pieterdd commented
See https://github.com/vikingco/prometheus-lighthouse-exporter/compare/master...vikingco:ii-833/setup-probes?expand=1

2021-06-07 09:22 UTC, closed without merging